---
dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

if: branch = master

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - yamllint .

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
