---
- name: Build the Docker image with the dependencies bundled in
  docker_image:
    source: build
    state: present
    force_tag: true
    force_source: true
    name: "temp-lambda-image-{{ name }}"
    build:
      path: "{{ context }}"
      pull: true
      dockerfile: "{{ role_path }}/runtimes/{{ runtime }}/Dockerfile"

- name: Copy the layer contents to the output directory
  docker_container:
    name: "temp-lambda-container-{{ name }}"
    image: "temp-lambda-image-{{ name }}"
    state: started
    restart: true
    cleanup: true
    recreate: true
    entrypoint:
      - /bin/bash
      - -c
      - "'cp /{{ layer_filename | quote }} /mnt/{{ layer_filename | quote }} && ls /mnt'"
    volumes:
      - "{{ output }}:/mnt/"

- name: Register that a build occurred
  set_fact:
    aws_lambda_dependency_layer_built: true
    aws_lambda_dependency_layer_zip: "{{ output }}/{{ layer_filename | quote }}"
