---
# tasks/main

- name: Check if the image already exists
  aws_layer_search:
    name: "{{ name }}"
  register: layer

- name: Destroy the layer if requested so
  when: state == 'absent' and mode == 'deploy'
  aws_lambda_layer:
    name: "{{ name }}"
    state: absent

- name: By default, no deployment or build occurs
  set_fact:
    aws_lambda_dependency_layer_built: false
    aws_lambda_dependency_layer_deployed: false
    aws_lambda_dependency_layer_zip: null

- name: Build the layer
  when: (mode == 'build') or (mode == 'deploy' and not layer.found and state == 'present')
  include_tasks: build.yml

- name: Deploy the layer
  when: mode == 'deploy' and not layer.found and state == 'present'
  include_tasks: deploy.yml

- name: Look up the image again
  aws_layer_search:
    name: "{{ name }}"
  register: layer

- name: Export the variables
  set_fact:
    aws_lambda_dependency_layer_name: "{{ name }}"
    aws_lambda_dependency_layer_arn: "{{ layer.layer_arn | d(None) }}"
    aws_lambda_dependency_layer_version: "{{ layer.version | d(None) }}"
    aws_lambda_dependency_layer_version_arn: "{{ layer.arn | d(None) }}"
    aws_lambda_dependency_layer_state: "{{ layer.found | ternary('present', 'absent') }}"
