---
- name: Cleanup
  hosts: all
  gather_facts: false

  tasks:
    - include_tasks: generate-suffix.yml

    - name: Destroy the temporary bucket
      s3_bucket:
        name: "temp-bucket-{{ temp_suffix }}"
        state: absent
