---
- name: Cleanup
  hosts: all
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - include_tasks: generate-suffix.yml

    - name: Destroy the temporary bucket
      s3_bucket:
        name: "temp-bucket-{{ temp_suffix }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Assure it's destroyed
      s3_bucket:
        name: "temp-bucket-{{ temp_suffix }}"
        state: absent

    - aws_lambda_layer:
        name: "temp-layer-{{ temp_suffix }}"
        state: absent
