---
- name: Cleanup
  hosts: all
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - include_tasks: assure-dependencies.yml

    - name: Destroy the temporary bucket
      s3_bucket:
        name: "temp-bucket-{{ temp_suffix }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Assure it's destroyed
      s3_bucket:
        name: "temp-bucket-{{ temp_suffix }}"
        state: absent

    - name: Destroy the layer
      aws_lambda_layer:
        name: "temp-layer-{{ temp_suffix }}"
        state: absent

    - name: Stop localstack
      docker_container:
        name: aws-lambda-dependency-layer-localstack
        image: localstack/localstack
        state: stopped
