---
dependency:
  name: galaxy

driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

lint:
  name: yamllint

platforms:
  - name: lambda-dependency-layer-test

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    v: true
  config_options:
    defaults:
      stdout_callback: debug

verifier:
  name: testinfra
  lint:
    name: flake8
