---
- name: Converge
  hosts: all
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - include_tasks: assure-dependencies.yml

    - include_role:
        name: aws_lambda_dependency_layer
      vars:
        name: "temp-layer-{{ temp_suffix }}"
        state: present
        context: ./tests/sample-data/ruby2.5
        output: "{{ molecule_ephemeral_directory }}/build"
        runtime: ruby2.5
        bucket: "temp-bucket-{{ temp_suffix }}"
        object_key: layer.zip

    - name: Save the exported variables
      copy:
        content: "{{ hostvars[inventory_hostname] | to_json }}"
        dest: "{{ molecule_ephemeral_directory }}/role-variables-main.json"
      changed_when: false
